In [12]:
# Raw data; list into array
import numpy as np
prices = np.array([1, 2, 3])
amounts = np.array([5, 10, 15])    

In [13]:
# Array form makes calculation faster and allows use vectorised operation
type(prices)
type(amounts)
# ndarray; n-dim array 

numpy.ndarray

In [14]:
# Computing the inner product of two vectors w.o. using lib.
revenue=0
for price, amount in zip(prices, amounts) :
    revenue+=price*amount

In [15]:
print(revenue)

70


In [16]:
# Computing the inner product using np.
revenue = np.dot(prices, amounts)

In [17]:
import tensorflow as tf

In [20]:
# Matrix representation (dim = 2)
M = np.array([[1,2,3], [4,5,6]])
print(M)
M

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
print(len(M), 'X',len(M[0]))

2 X 3


In [ ]:
# Matrix representation (dim = 3)
